use_frameworks!

target 'PersistentStorageSerializable_Example' do
  pod 'PersistentStorageSerializable', :path => '../'

  target 'PersistentStorageSerializable_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
